x = int(input("Enter first number: "))
y = int(input("Enter second number: "))
p = x+y
print("Sum =", p)
s = x-y
print("Subtraction =", s)
mul = x*y
print("Multiplication =", mul)
div = x/y
print("Division =", div)